export const subRfqWriteInfo = {
    "model": {title : 'MODEL'},
    "quantity": {title : '수량'},
    "unit": {title : '수량'},
    "currency": {title : 'CURR'},
    "net": {title : 'NET/P'},
    // "sentStatus": {title : '납기'},
    // "serialNumber": {title : '시리얼넘버'},
    // "replySummaryID": {title : '시리얼넘버'},
    "unitPrice": {title : '단가'},
    // "currencyUnit":   {title : '단위'},
    "deliveryDate": {title : '납기'},
    "content": {title : '내용'},
    "replyDate":  {title : '회신일'},
    "remarks":  {title : '비고'},
}